// APP/src/app/invoice-templates/modern-template/modern-template.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { InvoiceDetails } from '../../models/InvoiceDetails';
import { CommonModule, DatePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-modern-template',
  standalone: true,
  imports: [CommonModule, FormsModule],
  providers: [DatePipe],
  templateUrl: './modern-template.component.html',
  styleUrl: './modern-template.component.css'
})
export class ModernTemplateComponent implements OnInit{

  @Input() invoice!: InvoiceDetails;

  constructor(private http: HttpClient) {}


  ngOnInit(): void {
  
     
  }



  

}

<div style="width: 21cm; min-height: 29.7cm; padding: 1cm; box-sizing: border-box; font-family: Arial, sans-serif; font-size: 12px; color: #333;">
  <!-- Top Section -->
  <div style="display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 1cm;">
    <!-- Company Info -->
    <div style="max-width: 50%;">
      <div style="margin-bottom: 0.3cm;">
        <img *ngIf="invoice.companyLogo" [src]="invoice.companyLogo" alt="Company Logo" style="max-height: 120px; width: auto; object-fit: contain;">
      </div>
      <h1 style="font-size: 16px; font-weight: bold; margin-bottom: 0.3cm;">{{invoice.companyName}}</h1>
      <div style="line-height: 1.2;">
        <p style="margin: 0; white-space: pre-line;">{{invoice.companyAddress}}</p>
        <p style="margin: 0;">{{invoice.companyEmail}}</p>
        <p style="margin: 0;">{{invoice.companyPhone}}</p>
      </div>
    </div>

    <!-- Invoice Title & Basic Info -->
    <div style="text-align: right;">
      <h2 style="font-size: 20px; font-weight: bold; margin-bottom: 0.3cm;">INVOICE</h2>
      <div style="background-color: #f4f4f4; padding: 0.3cm; border-radius: 3px; display: inline-block;">
        <div style="font-size: 12px; color: #555;">Invoice Number</div>
        <div style="font-size: 14px; font-weight: bold; color: #333;">#{{invoice.invoiceNo}}</div>
      </div>
    </div>
  </div>

  <!-- Billing Info -->
  <div style="display: flex; justify-content: space-between; margin-bottom: 1cm;">
    <!-- Bill To -->
    <div style="width: 48%; background-color: #f9f9f9; padding: 0.8cm; border-radius: 3px; box-sizing: border-box;">
      <h3 style="font-size: 12px; font-weight: bold; margin-bottom: 0.3cm;">BILL TO</h3>
      <div>
        <p style="margin: 0; font-size: 12px; font-weight: bold;">{{invoice.client.name}}</p>
        <div style="line-height: 1.2; font-size: 11px; color: #666;">
          <p style="margin: 0; white-space: pre-line;">{{invoice.client.address}}</p>
          <p style="margin: 0;">{{invoice.client.email}}</p>
          <p style="margin: 0;">{{invoice.client.phone}}</p>
        </div>
      </div>
    </div>

    <!-- Invoice Details -->
    <div style="width: 48%; background-color: #f9f9f9; padding: 0.8cm; border-radius: 3px; box-sizing: border-box;">
      <h3 style="font-size: 12px; font-weight: bold; margin-bottom: 0.3cm;">INVOICE INFO</h3>
      <div style="line-height: 1.4; font-size: 11px; color: #666;">
        <div style="display: flex; justify-content: space-between;">
          <span>Issue Date:</span>
          <span style="font-weight: bold; color: #333;">{{invoice.issueDate | date:'mediumDate'}}</span>
        </div>
        <div style="display: flex; justify-content: space-between;">
          <span>Due Date:</span>
          <span style="font-weight: bold; color: #333;">{{invoice.dueDate | date:'mediumDate'}}</span>
        </div>
        <div style="display: flex; justify-content: space-between; border-top: 1px solid #ddd; padding-top: 0.3cm; margin-top: 0.3cm;">
          <span>Amount Due:</span>
          <span style="font-size: 14px; font-weight: bold; color: #333;">{{invoice.total | currency:invoice.currency}}</span>
        </div>
      </div>
    </div>
  </div>

  <!-- Items Table -->
  <div style="margin-bottom: 1.5cm;">
    <table style="width: 100%; border-collapse: collapse; font-size: 11px;">
      <thead>
        <tr style="background-color: #f4f4f4; border-bottom: 2px solid #ddd;">
          <th style="text-align: left; padding: 0.3cm; font-weight: bold;">Description</th>
          <th style="text-align: right; padding: 0.3cm; font-weight: bold;">Qty</th>
          <th style="text-align: right; padding: 0.3cm; font-weight: bold;">Rate</th>
          <th style="text-align: right; padding: 0.3cm; font-weight: bold;">Amount</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let item of invoice.invoiceItems" style="border-bottom: 1px solid #eee;">
          <td style="padding: 0.3cm 0;">{{item.description}}</td>
          <td style="text-align: right; padding: 0.3cm 0;">{{item.quantity}}</td>
          <td style="text-align: right; padding: 0.3cm 0;">{{item.price | currency:invoice.currency}}</td>
          <td style="text-align: right; padding: 0.3cm 0; font-weight: bold;">{{item.quantity * item.price | currency:invoice.currency}}</td>
        </tr>
      </tbody>
    </table>
  </div>

  <!-- Totals Section -->
  <div style="margin-bottom: 1.5cm; text-align: right;">
    <div style="display: flex; justify-content: flex-end; font-size: 12px; margin-bottom: 0.3cm;">
      <div style="width: 180px; text-align: left;">Subtotal:</div>
      <div style="width: 100px; text-align: right;">{{invoice.subtotal | currency:invoice.currency}}</div>
    </div>
    <div style="display: flex; justify-content: flex-end; font-size: 12px; margin-bottom: 0.3cm;">
      <div style="width: 180px; text-align: left;">Tax ({{invoice.taxRate}}%):</div>
      <div style="width: 100px; text-align: right;">{{invoice.tax | currency:invoice.currency}}</div>
    </div>
    <div style="display: flex; justify-content: flex-end; font-size: 14px; font-weight: bold; color: #333;">
      <div style="width: 180px; text-align: left;">Total:</div>
      <div style="width: 100px; text-align: right;">{{invoice.total | currency:invoice.currency}}</div>
    </div>
  </div>

  <!-- Notes & Terms -->
  <div style="margin-bottom: 1cm;">
    <h3 style="font-size: 12px; font-weight: bold;">Notes</h3>
    <p style="font-size: 11px; color: #666; line-height: 1.4;">{{invoice.notes}}</p>
    <h3 style="font-size: 12px; font-weight: bold;">Terms & Conditions</h3>
    <p style="font-size: 11px; color: #666; line-height: 1.4;">{{invoice.termsAndConditions}}</p>
  </div>


  <!-- Signature Section -->
<div *ngIf="invoice.signatureImage" style="display: flex; justify-content: space-between; margin-top: 2cm;">
  <!-- Authorized Signature -->
  <div style="text-align: center;">
    <img 
      [src]="invoice.signatureImage" 
      alt="Authorized Signature" 
      style="max-width: 180px; max-height: 60px; margin-bottom: 0.3cm;" />
      <p style="font-size: 11px; color: #666; margin: 0;">
        Signed on: {{ invoice.signatureDate | date: 'mediumDate' }}
      </p>
  </div>
</div>



</div>

// src/components/invoices/InvoiceTemplates/ModernTemplate.tsx
import { format } from 'date-fns';
import { Invoice } from '@/types';

interface ModernTemplateProps {
  invoice: Invoice;
  companyLogo?: string;
  companyDetails: {
    name: string;
    address: string;
    email: string;
    phone: string;
    website?: string;
  };
}

export function ModernTemplate({ invoice, companyLogo, companyDetails }: ModernTemplateProps) {
  return (
    <div className="bg-white p-8 text-black">
      {/* Header */}
      <div className="flex justify-between">
        <div>
          {companyLogo ? (
            <img src={companyLogo} alt="Company Logo" className="h-16 w-auto object-contain" />
          ) : (
            <h1 className="text-3xl font-bold">{companyDetails.name}</h1>
          )}
          <div className="mt-2 text-sm text-gray-600">
            <p>{companyDetails.address}</p>
            <p>{companyDetails.phone}</p>
            <p>{companyDetails.email}</p>
            {companyDetails.website && <p>{companyDetails.website}</p>}
          </div>
        </div>
        <div className="text-right">
          <h2 className="text-4xl font-bold text-gray-800">INVOICE</h2>
          <p className="mt-2 text-gray-600">#{invoice.number}</p>
          <p className="text-gray-600">
            Date: {format(new Date(invoice.createdAt), 'MMM dd, yyyy')}
          </p>
          <p className="text-gray-600">
            Due Date: {format(new Date(invoice.dueDate), 'MMM dd, yyyy')}
          </p>
        </div>
      </div>

      {/* Client Info */}
      <div className="mt-8">
        <h3 className="text-lg font-semibold text-gray-800">Bill To:</h3>
        <div className="mt-2">
          <p className="font-medium">{invoice.clientName}</p>
          <p className="text-gray-600">[Client Address]</p>
          <p className="text-gray-600">[Client Email]</p>
        </div>
      </div>

      {/* Invoice Items */}
      <div className="mt-8">
        <table className="w-full">
          <thead>
            <tr className="border-b-2 border-gray-200 text-left">
              <th className="pb-4 text-gray-600">Description</th>
              <th className="pb-4 text-gray-600">Quantity</th>
              <th className="pb-4 text-gray-600">Rate</th>
              <th className="pb-4 text-right text-gray-600">Amount</th>
            </tr>
          </thead>
          <tbody>
            {invoice.items.map((item) => (
              <tr key={item.id} className="border-b border-gray-100">
                <td className="py-4">{item.description}</td>
                <td className="py-4">{item.quantity}</td>
                <td className="py-4">${item.rate.toFixed(2)}</td>
                <td className="py-4 text-right">${item.amount.toFixed(2)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Totals */}
      <div className="mt-8 flex justify-end">
        <div className="w-64">
          <div className="flex justify-between border-b border-gray-100 py-2">
            <span className="font-medium">Subtotal:</span>
            <span>${invoice.subtotal.toFixed(2)}</span>
          </div>
          <div className="flex justify-between border-b border-gray-100 py-2">
            <span className="font-medium">Tax ({invoice.taxRate}%):</span>
            <span>${invoice.taxAmount.toFixed(2)}</span>
          </div>
          <div className="flex justify-between py-2 text-lg font-bold">
            <span>Total:</span>
            <span>${invoice.total.toFixed(2)}</span>
          </div>
        </div>
      </div>

      {/* Notes */}
      <div className="mt-8 border-t border-gray-200 pt-8">
        <h4 className="font-semibold text-gray-800">Notes:</h4>
        <p className="mt-2 text-gray-600">
          Thank you for your business. Please make payment within {format(new Date(invoice.dueDate), 'MMM dd, yyyy')}.
        </p>
      </div>

      {/* Payment Info */}
      <div className="mt-8">
        <h4 className="font-semibold text-gray-800">Payment Details:</h4>
        <div className="mt-2 text-sm text-gray-600">
          <p>Bank: [Bank Name]</p>
          <p>Account: [Account Number]</p>
          <p>SWIFT: [SWIFT Code]</p>
        </div>
      </div>
    </div>
  );
}
