// src/components/invoices/InvoiceTemplates/ModernTemplate.tsx
import { format } from 'date-fns';
import { Invoice } from '@/types';

interface ModernTemplateProps {
  invoice: Invoice;
  companyLogo?: string;
  companyDetails: {
    name: string;
    address: string;
    email: string;
    phone: string;
    website?: string;
  };
}

export function ModernTemplate({ invoice, companyLogo, companyDetails }: ModernTemplateProps) {
  return (
    <div className="bg-white p-8 text-black">
      {/* Header */}
      <div className="flex justify-between">
        <div>
          {companyLogo ? (
            <img src={companyLogo} alt="Company Logo" className="h-16 w-auto object-contain" />
          ) : (
            <h1 className="text-3xl font-bold">{companyDetails.name}</h1>
          )}
          <div className="mt-2 text-sm text-gray-600">
            <p>{companyDetails.address}</p>
            <p>{companyDetails.phone}</p>
            <p>{companyDetails.email}</p>
            {companyDetails.website && <p>{companyDetails.website}</p>}
          </div>
        </div>
        <div className="text-right">
          <h2 className="text-4xl font-bold text-gray-800">INVOICE</h2>
          <p className="mt-2 text-gray-600">#{invoice.number}</p>
          <p className="text-gray-600">
            Date: {format(new Date(invoice.createdAt), 'MMM dd, yyyy')}
          </p>
          <p className="text-gray-600">
            Due Date: {format(new Date(invoice.dueDate), 'MMM dd, yyyy')}
          </p>
        </div>
      </div>

      {/* Client Info */}
      <div className="mt-8">
        <h3 className="text-lg font-semibold text-gray-800">Bill To:</h3>
        <div className="mt-2">
          <p className="font-medium">{invoice.clientName}</p>
          <p className="text-gray-600">[Client Address]</p>
          <p className="text-gray-600">[Client Email]</p>
        </div>
      </div>

      {/* Invoice Items */}
      <div className="mt-8">
        <table className="w-full">
          <thead>
            <tr className="border-b-2 border-gray-200 text-left">
              <th className="pb-4 text-gray-600">Description</th>
              <th className="pb-4 text-gray-600">Quantity</th>
              <th className="pb-4 text-gray-600">Rate</th>
              <th className="pb-4 text-right text-gray-600">Amount</th>
            </tr>
          </thead>
          <tbody>
            {invoice.items.map((item) => (
              <tr key={item.id} className="border-b border-gray-100">
                <td className="py-4">{item.description}</td>
                <td className="py-4">{item.quantity}</td>
                <td className="py-4">${item.rate.toFixed(2)}</td>
                <td className="py-4 text-right">${item.amount.toFixed(2)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Totals */}
      <div className="mt-8 flex justify-end">
        <div className="w-64">
          <div className="flex justify-between border-b border-gray-100 py-2">
            <span className="font-medium">Subtotal:</span>
            <span>${invoice.subtotal.toFixed(2)}</span>
          </div>
          <div className="flex justify-between border-b border-gray-100 py-2">
            <span className="font-medium">Tax ({invoice.taxRate}%):</span>
            <span>${invoice.taxAmount.toFixed(2)}</span>
          </div>
          <div className="flex justify-between py-2 text-lg font-bold">
            <span>Total:</span>
            <span>${invoice.total.toFixed(2)}</span>
          </div>
        </div>
      </div>

      {/* Notes */}
      <div className="mt-8 border-t border-gray-200 pt-8">
        <h4 className="font-semibold text-gray-800">Notes:</h4>
        <p className="mt-2 text-gray-600">
          Thank you for your business. Please make payment within {format(new Date(invoice.dueDate), 'MMM dd, yyyy')}.
        </p>
      </div>

      {/* Payment Info */}
      <div className="mt-8">
        <h4 className="font-semibold text-gray-800">Payment Details:</h4>
        <div className="mt-2 text-sm text-gray-600">
          <p>Bank: [Bank Name]</p>
          <p>Account: [Account Number]</p>
          <p>SWIFT: [SWIFT Code]</p>
        </div>
      </div>
    </div>
  );
}

// APP/src/app/components/invoiceTemplates/modern-template/modern-template.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { InvoiceDetails } from '../../../models/create-invoice.interface';
import { CommonModule, DatePipe } from '@angular/common';

@Component({
  selector: 'app-modern-template',
  standalone: true,
  imports: [CommonModule],
  providers: [DatePipe],
  templateUrl: './modern-template.component.html',
  styleUrl: './modern-template.component.css'
})
export class ModernTemplateComponent implements OnInit{

  @Input() invoice!: InvoiceDetails;

  ngOnInit(): void {
    // // Hardcoded test data
    // this.invoice = {
    //   invoiceNumber: 'INV-2024-001',
    //   issueDate: new Date('2024-02-21'),
    //   dueDate: new Date('2024-03-21'),
    //   templateId: 'modern-blue', // Added this line
    //   company: {
    //     name: 'Tech Solutions Ltd',
    //     address: '123 Business Park\nSilicon Valley, CA 94025',
    //     email: 'contact@techsolutions.com',
    //     phone: '+1 (555) 123-4567',
    //     logo: 'https://i.pinimg.com/736x/71/b3/e4/71b3e4159892bb319292ab3b76900930.jpg'
    //   },
    //   client: {
    //     name: 'Acme Corporation',
    //     address: '456 Corporate Avenue\nNew York, NY 10001',
    //     email: 'billing@acmecorp.com',
    //     phone: '+1 (555) 987-6543'
    //   },
    //   items: [
    //     {
    //       description: 'Website Development',
    //       quantity: 1,
    //       price: 5000.00,
    //       amount: 5000.00
    //     }
    //   ],
    //   subtotal: 9000.00,
    //   taxRate: 18,
    //   tax: 1620.00,
    //   total: 10620.00,
    //   notes: 'Thank you for your business. We look forward to working with you again!',
    //   terms: '1. Payment is due within 30 days\n2. Please make payment to the bank account provided\n3. Late payments are subject to a 5% fee',
    //   signature: {
    //     name: 'John Smith',
    //     date: new Date('2024-02-21')
    //   }
    // };
  }



  

}

<div class="bg-white w-[21cm] min-h-[29.7cm] p-[2cm]">
    <!-- Top Section -->
    <div class="flex justify-between items-start mb-16">
      <!-- Company Info -->
      <div class="max-w-[50%]">
        <div class="mb-6">
            <img *ngIf="invoice.company.logo" 
                 [src]="invoice.company.logo" 
                 alt="Company Logo"
                 class="max-h-32 w-auto object-contain">
          </div>
        <h1 class="text-3xl font-bold text-gray-900 mb-6">{{invoice.company.name}}</h1>
        <div class="text-gray-600 space-y-1 text-sm">
          <p style="white-space: pre-line">{{invoice.company.address}}</p>
          <p>{{invoice.company.email}}</p>
          <p>{{invoice.company.phone}}</p>
        </div>
      </div>

      <!-- Invoice Title & Basic Info -->
      <div class="text-right">
        <div class="text-5xl font-bold text-gray-900 mb-4">INVOICE</div>
        <div class="inline-block bg-indigo-50 rounded-lg px-4 py-3">
          <div class="text-sm text-gray-500">Invoice Number</div>
          <div class="text-xl font-semibold text-indigo-600">#{{invoice.invoiceNumber}}</div>
        </div>
      </div>
    </div>

    <!-- Billing Info Grid -->
    <div class="grid grid-cols-2 gap-20 mb-16">
      <!-- Bill To -->
      <div class="bg-gray-50 rounded-2xl p-6">
        <h2 class="text-sm font-semibold text-gray-500 mb-4">BILL TO</h2>
        <div class="space-y-2">
          <div class="text-xl font-bold text-gray-900">{{invoice.client.name}}</div>
          <div class="text-gray-600 space-y-1 text-sm">
            <p style="white-space: pre-line">{{invoice.client.address}}</p>
            <p>{{invoice.client.email}}</p>
            <p>{{invoice.client.phone}}</p>
          </div>
        </div>
      </div>

      <!-- Invoice Details -->
      <div class="bg-gray-50 rounded-2xl p-6">
        <h2 class="text-sm font-semibold text-gray-500 mb-4">INVOICE INFO</h2>
        <div class="space-y-3">
          <div class="flex justify-between items-center">
            <span class="text-gray-600">Issue Date:</span>
            <span class="font-medium text-gray-900">{{invoice.issueDate | date:'mediumDate'}}</span>
          </div>
          <div class="flex justify-between items-center">
            <span class="text-gray-600">Due Date:</span>
            <span class="font-medium text-gray-900">{{invoice.dueDate | date:'mediumDate'}}</span>
          </div>
          <div class="flex justify-between items-center pt-2 border-t border-gray-200">
            <span class="text-gray-600">Amount Due:</span>
            <span class="text-xl font-bold text-indigo-600">{{invoice.total | currency}}</span>
          </div>
        </div>
      </div>
    </div>

    <!-- Items Table -->
    <div class="mb-16">
      <table class="w-full" style="border-collapse: collapse">
        <thead>
          <tr class="border-b-2 border-gray-200">
            <th class="py-4 text-left text-gray-500 font-semibold">Description</th>
            <th class="py-4 text-right text-gray-500 font-semibold" style="width: 100px">Qty</th>
            <th class="py-4 text-right text-gray-500 font-semibold" style="width: 150px">Rate</th>
            <th class="py-4 text-right text-gray-500 font-semibold" style="width: 150px">Amount</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let item of invoice.items" class="border-b border-gray-100">
            <td class="py-4">
              <div class="font-medium text-gray-900">{{item.description}}</div>
            </td>
            <td class="py-4 text-right text-gray-600">{{item.quantity}}</td>
            <td class="py-4 text-right text-gray-600">{{item.price | currency}}</td>
            <td class="py-4 text-right font-medium text-gray-900">{{item.amount | currency}}</td>
          </tr>
        </tbody>
      </table>
    </div>



    <!-- Totals Section -->
    <div class="flex justify-end mb-16">
      <div class="w-96 bg-gray-50 rounded-2xl p-6 space-y-3">
        <div class="flex justify-between text-gray-600">
          <span>Subtotal</span>
          <span>{{invoice.subtotal | currency}}</span>
        </div>
        
        <!-- Simplified Tax Section -->
        <div class="flex justify-between text-gray-600">
          <span>Tax Rate</span>
          <span>{{invoice.taxRate}}%</span>
        </div>
        <div class="flex justify-between text-gray-600">
          <span>Total Tax</span>
          <span>{{invoice.tax | currency}}</span>
        </div>
        
        <div class="flex justify-between pt-3 border-t border-gray-200">
          <span class="text-lg font-bold text-gray-900">Total</span>
          <span class="text-lg font-bold text-indigo-600">{{invoice.total | currency}}</span>
        </div>
      </div>
    </div>

    <!-- Notes & Terms -->
    <div class="grid grid-cols-2 gap-8 mb-16">
      <div *ngIf="invoice.notes" class="bg-yellow-50 rounded-2xl p-6">
        <h3 class="text-sm font-semibold text-yellow-800 mb-2">Notes</h3>
        <p class="text-sm text-yellow-800" style="white-space: pre-line">{{invoice.notes}}</p>
      </div>
      <div *ngIf="invoice.terms" class="bg-blue-50 rounded-2xl p-6">
        <h3 class="text-sm font-semibold text-blue-800 mb-2">Terms & Conditions</h3>
        <p class="text-sm text-blue-800" style="white-space: pre-line">{{invoice.terms}}</p>
      </div>
    </div>

    <div class="border-t-2 border-gray-100 pt-8">
      <div class="flex justify-between">
        <div class="w-64">
          <div *ngIf="invoice.signature?.image" class="mb-4">
            <!-- <img [src]="invoice.signature.image" 
                 alt="Signature" 
                 class="max-h-16 w-auto"> -->
          </div>
          <div class="border-b-2 border-gray-900 pb-1">
            <!-- {{invoice.signature?.name}} -->
          </div>
          <div class="text-sm text-gray-600 mt-1">Authorized Signature</div>
        </div>
        <div class="w-64 text-right">
          <div class="border-b-2 border-gray-900 pb-1">
            <!-- {{invoice.signature?.date | date:'mediumDate'}} -->
          </div>
          <div class="text-sm text-gray-600 mt-1">Date</div>
        </div>
      </div>
    </div>
  </div>
